### ISSUE TITLE
Tmux Pane Boundaries Made of Strange Characters

### ISSUE THREAD

**Issue by dwtj** [zeit/hyperterm#139]
I'm using:

- Mac OS X v10.11.5
- Tmux v2.2  (No `.tmux.conf` file used)
- HyperTerm v0.4.5

Tmux should look something like this (as seen here in iTerm 2 v3.0.5):

<img width="680" alt="screen shot 2016-07-15 at 7 37 14 pm" src="https://cloud.githubusercontent.com/assets/2457848/16891762/e7fdb950-4ac4-11e6-8050-80fa6073da57.png">

However, here's the kind of thing that I am consistently seeing when using tmux within HyperTerm:

<img width="830" alt="screen shot 2016-07-15 at 7 35 28 pm" src="https://cloud.githubusercontent.com/assets/2457848/16891756/b9e94f66-4ac4-11e6-9ceb-56c3c0d492ad.png">

And this is what it looks like if the cursor is in the top pane:

<img width="662" alt="screen shot 2016-07-15 at 7 38 06 pm" src="https://cloud.githubusercontent.com/assets/2457848/16891715/24199efa-4ac4-11e6-9ff6-544a66fe37b5.png">

And this is what it looks like if the session is open in another smaller terminal:

<img width="742" alt="screen shot 2016-07-15 at 7 37 11 pm" src="https://cloud.githubusercontent.com/assets/2457848/16891758/ceec4440-4ac4-11e6-9e3f-39847bd4daed.png">

**Comment by x** [comment]
There seem to be some general unicode issues. For example,

**Comment by x** [comment]
There seem to be some general unicode issues. For example, if I run a script 
```bash
echo "💩"
```
in iterm, it echos 💩 to STDOUT.

But in hyperterm I get the unicode replacement character.

**Comment by x** [comment]
A temporary solution would be to force tmux to use ascii characters for drawing borders. 

Add to your tmux.conf
```
set-option -ga terminal-overrides ',*:enacs@:smacs@:rmacs@:acsc@'
```

**Comment by dwtj** [comment]
That did the trick for me! Thanks for the workaround, @x.

**Comment by x** [comment]
Another thing that seems to have worked for me is forcing tmux to be in unicode mode by using `tmux -u` (in my .bashrc I've just set `alias tmux="tmux -u"`).

Maybe this isn't an issue with displaying unicode after all and rather an issue with the programs misunderstanding what the terminal understands?

**Comment by michaeljosephrosenthal** [comment]
@x that also made vim's NERDTree arrows work 👍

**Comment by x** [comment]
I'm not sure about anyone else, but I'm no longer seeing this issue in 0.7.1

I think this issue can be closed.

**Comment by spinningarrow** [comment]
I'm still seeing this issue on HyperTerm 0.7.1.36
![image](https://cloud.githubusercontent.com/assets/1797328/17560119/6b620394-5f53-11e6-86c1-23e867afcb9c.png)

**Comment by ajorgensen** [comment]
I am also seeing this issue even with @x suggestions.
![image](https://cloud.githubusercontent.com/assets/509779/18318410/999bd0c6-74ef-11e6-8049-2b50532c9b32.png)

tmux.conf:
```
set-option -ga terminal-overrides ',*:enacs@:smacs@:rmacs@:acsc@'
```

Command: `tmux -u -f ./tmux.conf`

Version: Version 0.7.1 (0.7.1.36)

**Comment by trevordmiller** [comment]
Same problem here. Here is a gif of me switching panes with the question mark characters. Couldn't duplicate in any other terminal emulator so it seems to be related to HyperTerm.

![tmux-question-marks](https://cloud.githubusercontent.com/assets/5497885/18531548/146f572e-7a94-11e6-9bbe-d3d0d68c3f98.gif)

**Comment by flybayer** [comment]
I'm no longer seeing this bug on master!

**Comment by ekmartin** [comment]
This was probably fixed by #769 :smile:

**Comment by trevordmiller** [comment]
I just ran a `brew cask install --force hyperterm` and I'm still getting the question marks when switching tmux panes as shown in my gif ^

Is this not latest HyperTerm with this fix in it? Or is this a separate issue?
![screen shot 2016-10-04 at 4 06 17 pm](https://cloud.githubusercontent.com/assets/5497885/19094303/a28fb20c-8a4c-11e6-9710-62912ad8f01d.png)

**Comment by flybayer** [comment]
It's only fixed on the current master branch. It'll be in the next `brew` release!
