### ISSUE TITLE
Could not update error notification ....

### ISSUE THREAD

**Issue by sarbbottam** [zeit/hyperterm#418]
I could see a repeated notification for some error.

<img width="326" alt="screen shot 2016-07-26 at 9 43 13 am" src="https://cloud.githubusercontent.com/assets/949380/17146989/802fc800-5315-11e6-9251-d3541574eea6.png">

I could see the following error in the console.

```
Error finding matching application co.zeit.hyperterm
```
<img width="808" alt="screen_shot_2016-07-26_at_9_40_15_am" src="https://cloud.githubusercontent.com/assets/949380/17146903/1d5d8aaa-5315-11e6-8677-7c21a8c32c38.png">

**Comment by paulyoung** [comment]
I've been seeing the same thing:

<img width="317" alt="screen shot 2016-07-26 at 9 47 26 am" src="https://cloud.githubusercontent.com/assets/84700/17147117/293ef2ae-5316-11e6-9f69-6410f22d2c68.png">

From Console.app:

```
7/26/16 9:40:47.651 AM HyperTerm[303]: Download completed to: file:///Users/py/Library/Caches/co.zeit.hyperterm.ShipIt/update.EUOF9pw/osx_64
```
```
7/26/16 9:45:58.317 AM HyperTerm[303]: Download completed to: file:///Users/py/Library/Caches/co.zeit.hyperterm.ShipIt/update.gfneXBr/osx_64

```
```
7/26/16 9:47:17.033 AM HyperTerm[95772]: Download completed to: file:///Users/py/Library/Caches/co.zeit.hyperterm.ShipIt/update.iR8Cipi/osx_64
```

**Comment by rauchg** [comment]
Should be fixed with the latest bundle. We switched to `electron-builder` from `electron-packager` and introduced a minor difference in the bundle (now resolved) that was throwing off the auto updates!

**Comment by sarbbottam** [comment]
Just installed the latest from the `.dmg`, still facing the same issue.

**Comment by rauchg** [comment]
I downloaded and inspected the latest which shows in the `Info.plist` the right bundle identifier (which is what the error you were seeing was about)

![image](https://cloud.githubusercontent.com/assets/13041/17147566/3962e08a-5318-11e6-910c-a33de3f60dd9.png)
