### ISSUE TITLE
Can't update plugins

### ISSUE THREAD

**Issue by montogeek** [zeit/hyperterm#89]
I am getting the `We could not find the 'npm' command. Make sure it\'s in $PATH` error when trying to update plugins.

I am using `nvm`, after adding the npm path to the $PATH, I still get the error.

This is how I am adding npm to the $PATH: `export PATH=~/.nvm/versions/v5.3.0/bin:$PATH`.

After checking the source code, this is the result of running `/usr/libexec/path_helper -s` on my Mac:
```
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/heroku/bin:/Users/montogeek/.nvm/versions/v5.3.0/bin:/usr/local/share/npm/bin:/Users/montogeek/.composer/vendor/bin:/usr/local/php5/bin:/Users/montogeek/.rvm/gems/ruby-2.2.4/bin:/Users/montogeek/.rvm/gems/ruby-2.2.4@global/bin:/Users/montogeek/.rvm/rubies/ruby-2.2.4/bin:/Users/montogeek/.rvm/bin"; export PATH;
MANPATH="/usr/share/man:/usr/local/share/man:/Users/montogeek/.nvm/versions/v5.3.0/share/man:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man"; export MANPATH;
```

And npm executable exist on that folder
<details>
```
montogeek ~/.nvm/versions/v5.3.0/bin [12:37 PM]→ 😀  ((HEAD detached at v0.17.2))
👉 ls
total 46536
drwxr-xr-x  47 montogeek  staff   1.6K Jul 12 16:33 .
drwxr-xr-x  12 montogeek  staff   408B Jul 12 09:11 ..
lrwxr-xr-x   1 montogeek  staff    31B Apr 19 12:43 a11y -> ../lib/node_modules/a11y/cli.js
lrwxr-xr-x   1 montogeek  staff    41B May 30 11:53 airsonos -> ../lib/node_modules/airsonos/bin/index.js
lrwxr-xr-x   1 montogeek  staff    42B May  9 14:13 babel -> ../lib/node_modules/babel-cli/bin/babel.js
lrwxr-xr-x   1 montogeek  staff    49B May  9 14:13 babel-doctor -> ../lib/node_modules/babel-cli/bin/babel-doctor.js
lrwxr-xr-x   1 montogeek  staff    59B May  9 14:13 babel-external-helpers -> ../lib/node_modules/babel-cli/bin/babel-external-helpers.js
lrwxr-xr-x   1 montogeek  staff    47B May  9 14:13 babel-node -> ../lib/node_modules/babel-cli/bin/babel-node.js
lrwxr-xr-x   1 montogeek  staff    35B Feb 22 10:52 bower -> ../lib/node_modules/bower/bin/bower
lrwxr-xr-x   1 montogeek  staff    41B May 13 02:05 browserify -> ../lib/node_modules/browserify/bin/cmd.js
lrwxr-xr-x   1 montogeek  staff    33B Feb  2 23:36 cloc -> ../lib/node_modules/cloc/lib/cloc
lrwxr-xr-x   1 montogeek  staff    41B Apr  4 09:30 depcheck -> ../lib/node_modules/depcheck/bin/depcheck
lrwxr-xr-x   1 montogeek  staff    39B Apr 24 22:37 dependo -> ../lib/node_modules/dependo/bin/dependo
lrwxr-xr-x   1 montogeek  staff    54B Mar 28 10:49 documentation -> ../lib/node_modules/documentation/bin/documentation.js
lrwxr-xr-x   1 montogeek  staff    45B Mar 25 18:18 esdoc -> ../lib/node_modules/esdoc/out/src/ESDocCLI.js
lrwxr-xr-x   1 montogeek  staff    40B Mar 12 11:19 eslint -> ../lib/node_modules/eslint/bin/eslint.js
lrwxr-xr-x   1 montogeek  staff    40B Jul 12 16:33 esw -> ../lib/node_modules/eslint-watch/bin/esw
lrwxr-xr-x   1 montogeek  staff    41B Jan 24 02:32 flint -> ../lib/node_modules/flint/cli/entry/flint
lrwxr-xr-x   1 montogeek  staff    47B Jan 24 02:32 flint-build -> ../lib/node_modules/flint/cli/entry/flint-build
lrwxr-xr-x   1 montogeek  staff    45B Jan 24 02:32 flint-new -> ../lib/node_modules/flint/cli/entry/flint-new
lrwxr-xr-x   1 montogeek  staff    45B Jan 24 02:32 flint-run -> ../lib/node_modules/flint/cli/entry/flint-run
lrwxr-xr-x   1 montogeek  staff    44B Jan 24 02:32 flint-up -> ../lib/node_modules/flint/cli/entry/flint-up
lrwxr-xr-x   1 montogeek  staff    48B Jan 24 02:32 flint-update -> ../lib/node_modules/flint/cli/entry/flint-update
lrwxr-xr-x   1 montogeek  staff    39B Mar  4 14:17 grunt -> ../lib/node_modules/grunt-cli/bin/grunt
lrwxr-xr-x   1 montogeek  staff    40B Apr 15 07:38 gulp -> ../lib/node_modules/gulp-cli/bin/gulp.js
lrwxr-xr-x   1 montogeek  staff    37B Feb  5 18:24 hexo -> ../lib/node_modules/hexo-cli/bin/hexo
lrwxr-xr-x   1 montogeek  staff    45B Jun 14 19:57 homebridge -> ../lib/node_modules/homebridge/bin/homebridge
lrwxr-xr-x   1 montogeek  staff    34B Apr 18 22:23 ied -> ../lib/node_modules/ied/bin/cmd.js
lrwxr-xr-x   1 montogeek  staff    60B Jul 11 10:07 left-behind -> ../lib/node_modules/left-behind/dist/left-behind.compiled.js
lrwxr-xr-x   1 montogeek  staff    42B Apr 13 09:15 lt -> ../lib/node_modules/localtunnel/bin/client
lrwxr-xr-x   1 montogeek  staff    35B Apr 24 22:12 madge -> ../lib/node_modules/madge/bin/madge
lrwxr-xr-x   1 montogeek  staff    32B Apr  4 15:11 mancy -> ../lib/node_modules/mancy/cli.js
lrwxr-xr-x   1 montogeek  staff    45B May  9 13:01 ncu -> ../lib/node_modules/npm-check-updates/bin/ncu
lrwxr-xr-x   1 montogeek  staff    50B Jul 11 09:49 next-update -> ../lib/node_modules/next-update/bin/next-update.js
-rwxr-xr-x   1 montogeek  staff    23M Dec 16  2015 node
lrwxr-xr-x   1 montogeek  staff    37B Apr  6 12:52 now -> ../lib/node_modules/now/build/bin/now
lrwxr-xr-x   1 montogeek  staff    38B Dec 16  2015 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x   1 montogeek  staff    59B May  9 13:01 npm-check-updates -> ../lib/node_modules/npm-check-updates/bin/npm-check-updates
lrwxr-xr-x   1 montogeek  staff    43B Feb  2 19:53 phantomjs -> ../lib/node_modules/phantomjs/bin/phantomjs
lrwxr-xr-x   1 montogeek  staff    37B Feb 16 10:46 rollup -> ../lib/node_modules/rollup/bin/rollup
lrwxr-xr-x   1 montogeek  staff    36B Feb  2 23:01 shjs -> ../lib/node_modules/shelljs/bin/shjs
lrwxr-xr-x   1 montogeek  staff    33B Feb  2 22:38 sloc -> ../lib/node_modules/sloc/bin/sloc
lrwxr-xr-x   1 montogeek  staff    36B Mar  8 16:49 spoof -> ../lib/node_modules/spoof/bin/cmd.js
lrwxr-xr-x   1 montogeek  staff    36B Jun 11 00:00 testem -> ../lib/node_modules/testem/testem.js
lrwxr-xr-x   1 montogeek  staff    36B Jun 12 14:00 vtop -> ../lib/node_modules/vtop/bin/vtop.js
lrwxr-xr-x   1 montogeek  staff    42B Jul  2 15:48 webpack -> ../lib/node_modules/webpack/bin/webpack.js
lrwxr-xr-x   1 montogeek  staff    39B Jun 10 20:25 yuidoc -> ../lib/node_modules/yuidocjs/lib/cli.js
```
</details>

This is the output when running `eval '/usr/libexec/path_helper -s' && npm prune --verbose && npm install --production --verbos` on `./hyperterm_plugins`:
<details>
```
montogeek ~/.hyperterm_plugins [12:50 PM]→ 😀
👉eval `/usr/libexec/path_helper -s` && npm prune --verbose && npm install --production --verbose
npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   '/Users/montogeek/.nvm/versions/v5.3.0/bin/npm',
npm verb cli   'prune',
npm verb cli   '--verbose' ]
npm info using npm@3.9.6
npm info using node@v0.12.1
npm verb node symlink /usr/local/bin/node
npm verb exit [ 0, true ]
npm info ok 
npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   '/Users/montogeek/.nvm/versions/v5.3.0/bin/npm',
npm verb cli   'install',
npm verb cli   '--production',
npm verb cli   '--verbose' ]
npm info using npm@3.9.6
npm info using node@v0.12.1
npm verb node symlink /usr/local/bin/node
npm verb correctMkdir /Users/montogeek/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/montogeek/.npm/_locks/staging-bf2c8b36661971db.lock for /Users/montogeek/.hyperterm_plugins/node_modules/.staging
npm verb unlock done using /Users/montogeek/.npm/_locks/staging-bf2c8b36661971db.lock for /Users/montogeek/.hyperterm_plugins/node_modules/.staging
npm info lifecycle hyperterm-plugins@0.0.1~preinstall: hyperterm-plugins@0.0.1
npm info linkStuff hyperterm-plugins@0.0.1
npm verb linkBins hyperterm-plugins@0.0.1
npm verb linkMans hyperterm-plugins@0.0.1
npm info lifecycle hyperterm-plugins@0.0.1~install: hyperterm-plugins@0.0.1
npm info lifecycle hyperterm-plugins@0.0.1~postinstall: hyperterm-plugins@0.0.1
npm verb exit [ 0, true ]
npm info ok
```
</details>

**Comment by digitaldesigndj** [comment]
I am having the same issue. It looks like the app is doing a check that interferes with npm via nvm loading. With nvm node is loaded via the .bashrc file. But it does not work. I found that running the same include command later (or just re-sourcing my .bashrc) will get npm working.

**Comment by kinduff** [comment]
I'm also able to reproduce when using a fresh install. Using nvm `0.29.0`, npm `1.4.3` and zsh `5.0.8 (x86_64-apple-darwin14.4.0)`. Re-sourcing `.zshrc` did not worked for me, I also extended the `PATH` variable with the direct path of my node installation and npm bin folder and executable paths.

**Comment by pauljakobwhite** [comment]
+1

**Comment by montogeek** [comment]
Fixed in https://github.com/zeit/hyperterm/releases/tag/0.6.0

**Comment by btholt** [comment]
I'm another nvm user and v0.6.0 did not solve this for me. I can neither install plugins and I still get the npm error message on startup. I'm looking into why it's happening.
